name = "http-api-d1"
main = "src/worker.ts"
compatibility_date = "2023-06-10"

# Replace this with your Cloudflare account ID
account_id = "d458dbe698b8eef41837f941d73bc5b3"

[[d1_databases]]
binding = "DB"
database_name = "db-enam"
database_id = "c89db32e-83f4-4e62-8cd7-7c8f97659029"
